# Generated by Django 4.1.3 on 2022-11-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('area_name', models.CharField(max_length=100, verbose_name='Название площадки')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа опереторов',
                'verbose_name_plural': 'Группы операторов',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('scheduled_time', models.PositiveSmallIntegerField(verbose_name='запланированное время')),
                ('ready', models.PositiveSmallIntegerField(verbose_name='Ready')),
                ('share_ready', models.FloatField(verbose_name='Доля ready')),
                ('adherence', models.FloatField(verbose_name='Соблюдение расписания')),
                ('sick_leave', models.PositiveSmallIntegerField(default=0, verbose_name='Больничные')),
                ('absenteeism', models.PositiveSmallIntegerField(default=0, verbose_name='Отсутсвия')),
                ('contact_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportapp.area', verbose_name='Площадка')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportapp.group', verbose_name='Группа')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportapp.jobtitle', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Данные отчета',
                'verbose_name_plural': 'Данные отчета',
                'ordering': ['date', 'contact_center', 'group', 'full_name'],
            },
        ),
    ]
