# Generated by Django 4.1.3 on 2022-11-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='contact_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_center', to='reportapp.area', verbose_name='Площадка'),
        ),
    ]
