# Generated by Django 4.1.3 on 2022-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_alter_reportdata_contact_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='absenteeism',
            field=models.FloatField(default=0, verbose_name='Отсутсвия'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='ready',
            field=models.FloatField(verbose_name='Ready'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='scheduled_time',
            field=models.FloatField(verbose_name='запланированное время'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='sick_leave',
            field=models.FloatField(default=0, verbose_name='Больничные'),
        ),
    ]
