# Generated by Django 4.1.3 on 2022-11-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_alter_reportdata_options_reportdata_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='position',
            field=models.CharField(max_length=100, unique=True, verbose_name='Должность'),
        ),
    ]
