# Generated by Django 4.1.3 on 2022-11-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0005_alter_area_area_name_alter_group_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata',
            name='share_ready',
        ),
    ]
